### ISSUE TITLE
HuggingFace Inference API cutting responses short

### ISSUE THREAD

**Issue by lucasvanmol** [NormXU/nougat-latex-ocr#2]
There seems to be an issue running the model on huggingface (https://huggingface.co/Norm/nougat-latex-base), as responses seem to be cut short. Take for example this image:

![Screenshot 2023-11-29 222445](https://github.com/NormXU/nougat-latex-ocr/assets/16979353/b602a9ef-687d-4747-90f2-ae594f5c8a1a)

The output is:

`\mathrm{{QFT}}:|x\rangle\mapsto{\frac`

I'm not sure if this is a temporary HF issue, or has the model been updated recently?

**Comment by NormXU** [comment]
@lucasvanmol I didn't update the model recently. Could you downgrade to `transformers==4.34.0` and try again? It's odd because I trained the model with a max sequence length of 800. You can check the config file [here](https://huggingface.co/Norm/nougat-latex-base/blob/main/config.json#L52). And I just ran the example in my environment (`transformers==4.34.0` ), the output looks good:

```
\\mathrm{QFT}:|x\\rangle\\mapsto\\frac{1}{\\sqrt{N}}\\sum_{k=0}^{N-1}\\omega_{N}^{x k}|k\\rangle.
```

It is probably an HF issue?

**Comment by lucasvanmol** [comment]
Yeah, running the model myself it seems perfectly fine. It's just the HF API that's causing trouble, but I'm not sure what the cause is, as it wasn't happening a few days ago.

**Comment by NormXU** [comment]
@lucasvanmol Yeah, I reproduced the bug. Several examples I once tested successfully now returned a short result as well.  This is definitely an hf issue.

**Comment by lucasvanmol** [comment]
I seem to have found a solution to this issue, but I'm still a bit baffled why this is suddenly needed. Adding in an extra `max_new_tokens` parameter gives the desired result:

```python
import requests
import base64

API_URL = "https://api-inference.huggingface.co/models/Norm/nougat-latex-base"
headers = {"Authorization": f"Bearer {API_TOKEN}"}

def query(q):
    response = requests.request("POST", API_URL, headers=headers, json=q)
    return response.json()

image = open("test.png", "rb")
image_b64 = base64.b64encode(image.read())
data = query({"inputs" : image_b64.decode("utf-8") , "parameters" : {"max_new_tokens" : 800}})
print(data)
image.close()
```

I think you might be able to include this parameter in the inference widget by adding something like this to the model card in HF:

```yaml
inference:
  parameters:
    max_new_tokens: 800
```
see https://huggingface.co/docs/hub/models-widgets#how-can-i-control-my-models-widget-inference-api-parameters

**Comment by NormXU** [comment]
@lucasvanmol I tried to add the parameters into the widget meta config, but it still fails to work. I open an issue [here](https://github.com/huggingface/huggingface.js/issues/487). Let's see what huggingface team thinks about it.

**Comment by felixswang** [comment]
Seems that all other checkpoints, including facebook/nougat-base, are having the same problem

**Comment by Shobhit1201** [comment]
I have finetuned on my custom dataset for handwritten equations. After downloading the weights .pth file and using it on colab directly it shows the following errors:

Repository Not Found for url: https://huggingface.co/try.pth/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

OSError: try.pth is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Can someblody please help how to use the new model weights for inference

**Comment by NormXU** [comment]
@Shobhit1201

Please check [this](https://github.com/NormXU/nougat-latex-ocr/issues/4#issuecomment-1962922999) thread.

**Comment by Shobhit1201** [comment]
thank you, it helps in inference. But if i need to use these weights for further training, what should i do?
@NormXU

**Comment by NormXU** [comment]
@Shobhit1201 The codebase supports further training from a certain checkpoint. Please check the codes [here](https://github.com/NormXU/nougat-latex-ocr/blob/e40ac044ab6b82ffedf8b631406819526913dbfd/experiment/donut_experiment.py#L148)

To utilize this feature, you need to specify the absolute path to the checkpoint in config.yaml file, which can be found [here](https://github.com/NormXU/nougat-latex-ocr/blob/main/config/base.yaml#L10)

**Comment by Shobhit1201** [comment]
@NormXU this worked, thank you!!
Now if i want to evaluate on my test set, and calculate token_acc and edit_dist, is there script for that as well?

**Comment by NormXU** [comment]
@Shobhit1201 Yes, there is. Check [this](https://github.com/NormXU/nougat-latex-ocr/blob/e40ac044ab6b82ffedf8b631406819526913dbfd/experiment/donut_experiment.py#L39). The eval func is used to calculate token_acc and edit_dis

**Comment by hem210** [comment]
@lucasvanmol Thanks for that suggestion! The `max_new_tokens` parameter worked for me. I was able to retrieve a longer response. 

Context:
Previously I was using: `max_tokens: 1000` which gave a truncated response. I replaced that with `max_new_tokens: 1000` and it gave a better result.

I think this is related to how HuggingFace Inference API endpoint gives response. I am using HTTP Request to fetch the response. In the response, it adds the prompt as a prefix to the response. So, how I understand is, the prompt tokens also get counted in the response tokens. Might be the case that, max new tokens is used to count just the response tokens explicitly. So giving a longer response in turn.

**Comment by Shobhit1201** [comment]
Two new errors coming now, 
Error 1: while installing the requirements:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 0.34.2 requires huggingface-hub>=0.21.0, but you have huggingface-hub 0.17.0 which is incompatible. 

Error 2: from huggingface_hub import split_torch_state_dict_into_shards
ImportError: cannot import name 'split_torch_state_dict_into_shards' from 'huggingface_hub' .

**Comment by NormXU** [comment]
@Shobhit1201 You can try to run

`pip install --upgrade huggingface-hub`

**Comment by Shobhit1201** [comment]
hey it was having dependency issue with the older version of transformers specified in the requirements file, so i upgraded both and it worked fine.

**Comment by Shobhit1201** [comment]
Hey, 
i used the inference script: 
model_name = "Norm/nougat-latex-base"
checkpoint_path = "/content/drive/MyDrive/nougat-base_epoch97_step18000_lr3.805302e-08_avg_loss0.01257_token_acc0.11251_edit_dis0.38271.pth"  # this is your fine-tuned checkpoint
device = "cuda" if torch.cuda.is_available() else "CPU"

### Initialize the model
model = VisionEncoderDecoderModel.from_pretrained(model_name).to(device)

### load the model weight
state_dict = torch.load(checkpoint_path, map_location=torch.device("cpu"))
model.load_state_dict(state_dict, strict=True)

output: <All keys matched successfully>

then this:
!python /content/nougat-latex-ocr/examples/run_latex_ocr.py --img_path "/content/1.png"

but getting the following error: from nougat_latex.util import process_raw_latex_code
ModuleNotFoundError: No module named 'nougat_latex'

majorly the error is with the nougat_latex module. It is not detected by other files
from nougat_latex import NougatLaTexProcessor
from nougat_latex.util import process_raw_latex_code
from nougat_latex import NougatLaTexProcessor

I have encountered the same error earlier also. Please help @NormXU

**Comment by NormXU** [comment]
@Shobhit1201

> ModuleNotFoundError: No module named 'nougat_latex'

The nougat_latex module is [here](https://github.com/NormXU/nougat-latex-ocr/tree/main/nougat_latex)

You need to download the source code first, or, if you prefer not to download the entire codebase, you can copy and paste the nougat_latex module.

**Comment by Shobhit1201** [comment]
hey @NormXU, I finetuned it on my custom dataset of mathematical equations but the model doesn't seem to improve even after increasing the resolution. What can I do to improve the performace on my dataset?
Is there any way to make changes in the model architecture?

**Comment by NormXU** [comment]
@Shobhit1201 I believe changing the model architecture should typically be the last action to take. First, I'd recommend examining your dataset—specifically, the height-to-width ratio distribution and the range of widths in the equation image clips. Next, consider adjusting the padding to better align with this distribution. Hope this helps!

**Comment by Shobhit1201** [comment]
I have a very varied set of equations like (736 * 63), (652 * 679), (1104 * 96), (984 * 964), (1256 * 328)...
Width Range: Min = 159, Max = 1562
Height Range: Min = 24, Max = 1168
Mean Width: 781.24, Mean Height: 320.87
Median Width: 758.0, Median Height: 295.0

What can i do. and what part of the code should i look at?

**Comment by NormXU** [comment]
@Shobhit1201 You can adjust the image preprocessing to ensure the training images are not rescale too much and keep the input images as close to their native resolutions as possible. Code [here](https://github.com/NormXU/nougat-latex-ocr/blob/main/nougat_latex/image_processor_img2latex.py#L20).

**Comment by Shobhit1201** [comment]
![52](https://github.com/user-attachments/assets/f566d36e-78db-487c-8727-8773dbe55ce5)
i want to train for these types of images, but unable to do even after adjusting the resolution. Can you please suggest some changes.

**Comment by NormXU** [comment]
@Shobhit1201
now I see why fine-tuning nougat-latex-ocr ckpt doesn't work on your dataset. The nougat-latex-ocr ckpt was mainly fine-tuned to parse single-line LaTeX equations clipped from documents. During training, I dropped samples with multiple lines of equations to ensure the model could perform well only on single-line LaTeX equations. Instead of further fine-tuning this version, you might consider using the original [nougat-base](https://huggingface.co/facebook/nougat-base), which was initially trained to transcribe a PDF page into markdown, whose input image resolution is closer to the one you post. The key problem you may need to research about is how to design the image preprocessing, I suppose.

Here’s my suggestion: Start with the original Nougat checkpoint and scale up your dataset. First, define several bins based on image height and width, grouping images with similar sizes. For instance, bin-0 could contain images with resolutions around (48, 600), while bin-1 could include images similar to the one you posted above. Then, train progressively from bin-0 to bin-1 by gradually increasing resolution. 

There are also many popular Document parsing models, such as [GOT](https://huggingface.co/stepfun-ai/GOT-OCR2_0). You can try to fine-tune this model with your dataset. 

Hope this can help!

**Comment by Shobhit1201** [comment]
@NormXU understood. But i am new to this therefore i am unable to understand how to train/finetune the original model. i tried to use the original model checkpoints in your version to finetune but it gives some error that weights are missing or unexpected but for inference it works fine. Could you please help how should i move forward. 

moreover in the original model it has a very different type of pdf dataset but mine is similar to yours. I am stuck.
Also i have a variety of pictures, only these big equations are not recognized correctly otherwise it recognizes most of the multiline equations.

**Comment by NormXU** [comment]
@Shobhit1201 Could you please open a new issue? I'm happy to help, but your problem is unrelated to this one.
