### ISSUE TITLE
Can't running python files

### ISSUE THREAD

**Issue by byueng** [NormXU/nougat-latex-ocr#6]
Guys, why can't I run example file which locates in "examples" folder. I see all packages I need is ok, but when I ran it said "ModuleNotFoundError: No module named 'nougat_latex'". First, I think there's no "__init__.py", then I made it. But it didn't work. I didn't see any discussion about it, so all of your python files work correctly? I feel so surpurised about it.

**Comment by NormXU** [comment]
@byueng  You may want to include the absolute path of your current directory in the sys.path list
