### ISSUE TITLE
Great work. I currently have millions of data that need to be trained. I would like to ask if it supports multi-gpu training?

### ISSUE THREAD

**Issue by pjpanadas** [NormXU/nougat-latex-ocr#7]
Or what needs to be changed to support multi-gpu training? 
I look forward to your reply.

**Comment by NormXU** [comment]
@pjpanadas Yes, the codebase supports DDP on a single node using the accelerate. If you have multiple nodes, I think you need to make some modifications.

**Comment by pjpanadas** [comment]
> @pjpanadas Yes, the codebase supports DDP on a single node using the accelerator. If you have multiple nodes, I think you need to make some modifications.

Could you please tell me what needs to be changed? I am new to this field and I don't know what needs to be changed. Thank you very much.

**Comment by NormXU** [comment]
@pjpanadas [This](https://huggingface.co/docs/accelerate/v0.12.0/en/basic_tutorials/notebook) tutorial can be helpful. I believe you need to at least update the accelerate configuration. Could you let me know how many nodes you have?
